### ISSUE TITLE
Recursion when os.path.split returns empty directory string

### ISSUE THREAD

**Issue by ModernMAK** [MAK-Relic-Tool/Issue-Tracker#47]
```powershell
PS C:\Users\Admin\Desktop> relic sga pack v2 test.arciv test.sga
```
```console
Traceback (most recent call last):
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\Scripts\relic.exe\__main__.py", line 7, in <module>
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\core\cli.py", line 168, in run
    return super().run()
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\core\cli.py", line 122, in run
    exit_code = self._run(ns, sys.argv)
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\core\cli.py", line 91, in _run
    result: Optional[int] = func(ns)
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\sga\v2\cli.py", line 69, in command
    elif not _check_parts(out_path):
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\sga\v2\cli.py", line 59, in _check_parts
    return _check_parts(d)
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\sga\v2\cli.py", line 59, in _check_parts
    return _check_parts(d)
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\sga\v2\cli.py", line 59, in _check_parts
    return _check_parts(d)
  [Previous line repeated 986 more times]
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\relic\sga\v2\cli.py", line 55, in _check_parts
    d, f = os.path.split(_path)
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 212, in split
    seps = _get_bothseps(p)
  
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 36, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ModernMAK** [comment]
Fixed in https://github.com/MAK-Relic-Tool/SGA-V2/commit/fbfc2b008bf45d75e5236f1666036dc393c75568
